# Generated by Django 2.2.15 on 2020-08-26 13:27

import api.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character_id', models.PositiveIntegerField(help_text='ex. 10', verbose_name='ID Character')),
                ('score', models.PositiveSmallIntegerField(help_text='ex. 3', validators=[api.validators.score_validation])),
            ],
        ),
    ]
